[package]
name = "fe-hir"
version = "0.23.0"
authors = ["The Fe Developers <snakecharmers@ethereum.org>"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/ethereum/fe"
description = "Provides HIR definition and lowering for Fe lang"

[dependencies]
# We may need to fix this to a specific version, 
# but I want to keep up with the latest version until the new Fe implemeentation is merged into the master.
salsa = { git = "https://github.com/salsa-rs/salsa", package = "salsa-2022" }
derive_more = "0.99"
cranelift-entity = "0.91"
num-bigint = "0.4"
num-traits = "0.2.15"
camino = "1.1.4"
rustc-hash = "1.1.0"
smallvec = "1.10.0"
paste = "1.0"
dot2 = "1.0"
strum = { version = "0.25", features = ["derive"] }
strum_macros = "0.25"

common = { path = "../common2", package = "fe-common2" }
parser = { path = "../parser2", package = "fe-parser2" }
macros = { path = "../macros", package = "fe-macros" }