[package]
authors = ["The Fe Developers <snakecharmers@ethereum.org>"]
edition = "2021"
name = "fe-compiler-test-utils"
version = "0.21.0-alpha"
license = "GPL-3.0-or-later"
repository = "https://github.com/ethereum/fe"

[dependencies]
ethabi = { default-features = false, features = ["full-serde"], version = "18.0" }
evm = { default-features = false, version = "0.37" }
evm-runtime = { default-features = false, version = "0.37" }
fe-common = {path = "../common", version = "^0.21.0-alpha"}
fe-driver = {path = "../driver", version = "^0.21.0-alpha"}
fe-yulc = {path = "../yulc", version = "^0.21.0-alpha", optional = true, features = ["solc-backend"]}
fe-analyzer = {path = "../analyzer", version = "^0.21.0-alpha"}
test-files = {path = "../test-files", package = "fe-test-files" }
hex = "0.4"
primitive-types = {version = "0.12", default-features = false, features = ["rlp"]}
serde_json = "1.0.64"
solc = { git = "https://github.com/Y-Nak/solc-rust", rev = "a647450", optional = true}
yultsur = {git = "https://github.com/g-r-a-n-t/yultsur", rev = "ae85470"}
indexmap = "1.6.2"
insta = { default-features = false, version = "1.26" }

# used by ethabi, we need to force the js feature for wasm support
getrandom = { version = "0.2.8", features = ["js"] }

[features]
solc-backend = ["fe-yulc", "solc", "fe-driver/solc-backend"]
