[package]
name = "fe-language-server"
version = "0.26.0"
edition = "2021"
authors = ["The Fe Developers <snakecharmers@ethereum.org>"]
license = "Apache-2.0"
repository = "https://github.com/ethereum/fe"
description = "An LSP language server for Fe lang"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
salsa = { git = "https://github.com/salsa-rs/salsa", version = "0.18" }
codespan-reporting = "0.11"
hir = { path = "../hir", package = "fe-hir" }
language-server-macros = { path = "../language-server-macros", package = "fe-language-server-macros" }
macros = { path = "../macros", package = "fe-macros" }
hir-analysis = { path = "../hir-analysis", package = "fe-hir-analysis" }
camino = "1.1.4"
clap = { version = "4.3", features = ["derive"] }
fe-analyzer = { path = "../analyzer", version = "^0.26.0" }
driver = { path = "../driver2", package = "fe-driver2" }
common = { path = "../common2", package = "fe-common2" }
anyhow = "1.0.71"
lsp-types = "0.94.0"
serde = "1.0.162"
serde_json = "1.0.96"
indexmap = "1.6.2"
rowan = "0.15.10"
fxhash = "0.2.1"
dir-test = "0.3"
fe-compiler-test-utils = { path = "../test-utils" }
log = "0.4"
patricia_tree = "0.6.2"
glob = "0.3.1"
url = "2.4.1"
tower-lsp = "0.20.0"
tokio = { version = "1.35.1", features = ["full", "io-std", "tracing"] }
tokio-macros = "2.2.0"
futures = "0.3.28"
tokio-stream = { version = "0.1.14", features = ["sync"] }
fork_stream = "0.1.0"
debounced = "0.1.0"
stream-operators = "0.1.1"
pin-project = "1.1.5"
merge-streams = "0.1.2"
futures-concurrency = "7.5.0"
console-subscriber = "0.2.0"
vfs = "0.12.0"
rust-embed = "8.3.0"
futures-batch = "0.6.1"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tracing-appender = "0.2.3"
