[package]
name = "vyper-compiler"
version = "0.1.0"
authors = ["Grant Wuerker <gwuerker@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vyper-parser = {path = "../parser", version = "0.1.0"}
serde_json = "1.0"
serde = "1.0"
