[package]
name = "fe-common"
version = "0.26.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/ethereum/fe"
description = "Provides HIR definition and lowering for Fe lang."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
camino.workspace = true
paste.workspace = true
salsa.workspace = true
semver.workspace = true
smol_str = "0.3.2"
rust-embed = { version = "8.5.0", features = ["debug-embed"] }

parser.workspace = true
ordermap = "0.5.5"
rustc-hash.workspace = true
