[package]
name = "fe-common"
version = "0.24.0"
authors = ["The Fe Developers <snakecharmers@ethereum.org>"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/ethereum/fe"

[dependencies]
fe-library = {path = "../library", version = "^0.24.0"}
tiny-keccak = { version = "2.0", features = ["keccak"] }
hex = "0.4"
codespan-reporting = "0.11.1"
serde = { version = "1", features = ["derive"] }
ron = "0.5.1"
difference = "2.0"
num-bigint = "0.4.3"
num-traits = "0.2.14"
once_cell = "1.8.0"
indexmap = "1.6.2"
smol_str = "0.1.21"
salsa = "0.16.1"
camino = "1.0.7"
walkdir = "2"
toml = "0.7.6"
path-clean = "1.0.1"
