[book]
authors = ["The Fe Developers <snakecharmers@ethereum.org>"]
language = "en"
multilingual = false
src = "src"
title = "The Fe Guide"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]