[book]
authors = ["The Fe Developers <snakecharmers@ethereum.org>"]
language = "en"
multilingual = false
src = "src"
title = "The Fe Guide"

[output.html]
additional-css = ["theme/reference.css"]

[output.linkcheck]
follow-web-links = true
warning-policy = "error"
exclude = [ 'github\.com' ]