[package]
name = "fe-yulc"
version = "0.20.0-alpha"
authors = ["The Fe Developers <snakecharmers@ethereum.org>"]
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/ethereum/fe"

[dependencies]
# This fork supports concurrent compilation, which is required for Rust tests.
solc = { git = "https://github.com/Y-Nak/solc-rust", rev = "a647450", optional = true}
serde_json = "1.0"
indexmap = "1.6.2"

[features]
solc-backend = ["solc"]
